version: "3.9"

services:
  node_express_app:
    container_name: node_express_app
    build: .
    ports:
      - "3000:3000"
    environment:
      - PG_DB=node_live_db
      - PG_USER=favot
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    depends_on:
      - node_express_db
    env_file:
      - .env
    volumes:
      - ./src:/app/src # Mount your local src directory to the container's src directory
      - ./prisma:/app/prisma # Mount your local prisma directory to the container's prisma directory
    command: >
      bash -c "npm run seed &&
               npm run docker:dev"

  node_express_db:
    container_name: node_express_db
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=favot
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}
